apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sf4-deployment
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: eu.gcr.io/meineapp/sf4:v20
        ports:
        - containerPort: 80
