apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
  name: sf4-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: port-1
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: app
  sessionAffinity: None
  type: LoadBalancer

#kubectl expose deployment go-deployment --type=LoadBalancer --name=my-service